name: .NET Core

on: 
   push:
     branches: [ main ]
   pull_request:
      branchs: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
      contents: read


    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Install Depedencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    # Gerar um dotnet pack do pacote nuget
    - nome: Pack
      run: dotnet pack --configuration Release
  
    # Inclua um dotnet no add source para github artifacts

    - name: Addd GitHub Package Source
      run: dotnet nuget add source https://nuget.pkg.github.com/JanioSantosSilva/index.json --name github --username JanioSantosSilva --password ${{ secrets.GITHUB_TOKEN}}

    # Inclua um dotnet nuget push para githubactions artifacts
    - name: Push to GitHub Packages
      run:  dotnet nuget push **/*.nupkg --source github --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN}}
      